# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  verify:
    docker:
      - image: hadolint/hadolint:v1.21.0-3-g68ed571-alpine
    steps:
      - checkout 
      - run:
          name: hadolint
          command: |
            hadolint --ignore DL3042 Dockerfile

  build:
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pwd
            ls -al 
            make setup venv install
            pip install pylint
            pylint --version
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            make venv pylint

workflows:
  default:
    jobs:
      - verify
      - build